### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-xjc#12]
I upgraded the plugin to be an AutoPlugin and to use a new version of xjc that has a Java 8 fix. Also, @timvlaer added the xjcBindings option and did some other cleanup

@retronym think we could cut a new version?

**Comment by benmccann** [comment]
@retronym I think this is another thing I won't have permission to do and will need your help for

**Comment by retronym** [comment]
I've just released 0.6

```
[info] Packaging /Users/jason/code/sbt-xjc/target/scala-2.10/sbt-0.13/sbt-xjc-0.6-javadoc.jar ...
[info] Done packaging.
[info] 	published sbt-xjc to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt.plugins/sbt-xjc/scala_2.10/sbt_0.13/0.6/jars/sbt-xjc.jar
[info] 	published sbt-xjc to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt.plugins/sbt-xjc/scala_2.10/sbt_0.13/0.6/srcs/sbt-xjc-sources.jar
[info] 	published sbt-xjc to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt.plugins/sbt-xjc/scala_2.10/sbt_0.13/0.6/docs/sbt-xjc-javadoc.jar
[info] 	published ivy to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt.plugins/sbt-xjc/scala_2.10/sbt_0.13/0.6/ivys/ivy.xml
[success] Total time: 13 s, completed 17/03/2015 1:26:18 PM
```

**Comment by benmccann** [comment]
A huge thank you!!!!!

**Comment by benmccann** [comment]
@retronym Thanks again for the release. I think there may be a problem with the build that was cut.

When I try to use the new version of the plugin I get the error message:

    java.lang.ClassCastException: Cannot cast com.github.retronym.sbtxjc.SbtXjcPlugin$ to sbt.Plugin

I don't quite understand why I'm getting this error. The contents of the message don't seem true to me. Also, the scripted tests still pass, so I'm not sure why they wouldn't get this error as well. [The only reference to this error I can find on the web suggests](https://groups.google.com/forum/#!topic/play-framework/pfkTRwmYf14) that perhaps doing a clean and then republishing a new version of the plugin might help.

**Comment by benmccann** [comment]
I think I got it figured out. @retronym can you do a clean build and publish a new version of sbt-xjc?

The published version sbt-xjc jar contains both an "sbt.plugins" and "sbt.autoplugins" file. It should only have the latter I believe. I only have an "sbt.autoplugins" in my locally built version. I'm guessing what happened is that these files are generated by the build and the library was published without doing a clean build, so it picked up an old "sbt.plugins" file that was left around on the file system from the previous time the library was built.

**Comment by retronym** [comment]
Done:

```
% jar tf target/scala-2.10/sbt-0.13/sbt-xjc-0.7.jar  | grep plugins
sbt/sbt.autoplugins
```

**Comment by benmccann** [comment]
Thanks. That worked!!
