### ISSUE TITLE
An option to put generated files in src_managed/main instead of /src_managed/main/xjc

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt-xjc#5]
sourceManaged in xjc ~= (_ / "xjc"), // e.g. /target/scala-2.8.1.final/src_managed/main/xjc

Can I override this somehow in my build?

**Comment by benmccann** [comment]
Is there a problem that the current setup causes you? What's the reason for wanting to be able to change it?

**Comment by francisdb** [comment]
Hmm, that was a while ago, probably related to intellij taking src_managed/main as source folder. (not sure if that's still the case) For my part you can close this ticket.

**Comment by benmccann** [comment]
Oh, yeah. I just tested and Eclipse totally hates it. I changed the default to not include "xjc": https://github.com/sbt/sbt-xjc/commit/226ff93ddcd0374aae0383b0a2a4e0282f7b7374

**Comment by francisdb** [comment]
To be honest I wonder what the best practice is. The docs seem to indicate you need to use a subdir:
http://www.scala-sbt.org/0.13.5/docs/Detailed-Topics/Classpaths.html

I see scalaxb also using a subdir.
https://github.com/eed3si9n/scalaxb/blob/master/sbt-scalaxb/src/main/scala/sbtscalaxb/Plugin.scala

Maybe the IDE plugins should be fixed instead...
I suggest you revert the commit
